### ISSUE TITLE
Issues for student 3174 & 3175 

### ISSUE THREAD

**Issue by LilyN11** [cosmicds/cosmicds#179]
1) The histogram generated from the seed data seems to very off.  this is the histogram that appeared when I tested the first student. However, this doesn’t make any sense because the seed data was at 18. In the second graph you can see the correct histogram for three students

![pasted image 0](https://user-images.githubusercontent.com/53539773/202525218-905418f3-409c-4b80-ac06-38377fe4fdb4.png)
![pasted image 0-1](https://user-images.githubusercontent.com/53539773/202525308-602ab52b-c171-405d-894c-7c5a2d62c5e9.png)

2) The professional data does not show up for me for either student. This is from the voila version of the app (I don't know how much of this stage is built yet and my other errors are in relation to this stage so let me know if I shouldn't be looking to closely at this stage yet)
![pasted image 0-2](https://user-images.githubusercontent.com/53539773/202525898-6e29dba7-cc51-433c-8c37-d441a587dd61.png)
![pasted image 0-3](https://user-images.githubusercontent.com/53539773/202525921-2becdff1-88a5-43ff-b77a-27a1f58157da.png)
![pasted image 0-4](https://user-images.githubusercontent.com/53539773/202525940-c2430b14-8d72-4fbd-bfdf-19e790077188.png)

**Comment by patudom** [comment]
These issues have been fixed.
