### ISSUE TITLE
Speech issues

### ISSUE THREAD

**Issue by patudom** [cosmicds/cosmicds#200]
I merged #195 and https://github.com/cosmicds/hubbleds/pull/130 to get ready for the file renaming tomorrow, but just so we can keep track, here are some lingering speech issues I noticed in my not-extensive testing (which @Carifio24 may already know about):

- The rate setting does not behave how I expect it should. To me, 2x means twice as fast as 1x, but at 2x, the speech was incomprehensibly fast. I chose a random blurb and timed how long it took to speak. At 1x, the duration was 31.6 sec. At 2x, it was 8.9 sec.
- In terms of reading a long blurb in its entirety, the reader did pretty well with the default voice. However, when I switched to a different voice, I ran into the issue where random chunks of the blurb were skipped over. The different voice I chose (Alex-en-US) read significantly more slowly than the default voice, so I wonder if that caused the problem.
- Just a suggestion - in the same way that the Google voices are prepended with Google in the dropdown, I wonder if it would help the user if we add Apple in front of the apple voices, and similarly for the Microsoft & Edge voices?

**Comment by Carifio24** [comment]
These are all good points. My thoughts:
* Yeah, clearly the mapping between the `rate` value and the actual reading speed is not linear. I'll do a few timing tests and work out the function that relates the two, and we can use that transformation to make the value that the student sees more sensible.
* I'll look into the differences in speed between voices. We may just need to reduce the time between pause-resume calls to accommodate more voices.
* The main thing will be whether we can identify which voice comes from where. It's often pretty easy for a human to tell by looking, but I'm not sure that this is stored anywhere in the `SpeechSynthesisVoice` object. But we should at least be able to come up with some heuristics based on e.g. the voice URI that will let us do good enough.

**Comment by Carifio24** [comment]
From dev meeting 3/29/2023:
* Run through a tensor of voices/browsers/OSes/rates, recording timing using the utterance's onstart and onend event handlers, to determine how the rate maps to the actual time ratio (time(rate=x) / time(rate=1)) for each voice
