### ISSUE TITLE
WWT controls & linked data selection

### ISSUE THREAD

**Issue by Carifio24** [cosmicds/cosmicds#6]
The main idea of this issue is to give us a place to discuss any issues we have with the glue-wwt viewer. I think I showed some of these at a previous meeting, but here are a few basic code snippets for controlling the WWT widget.

To access the WWT viewer from the prototype app:

`wwt_viewer = app._viewer_handlers['wwt_viewer']`

We can access the `WWTJupyterWidget` that lives in the viewer using the `_wwt` member value:

`wwt_widget = wwt_viewer._wwt`

The WWT viewer provides methods for obtaining the current field of view and the center (RA, Dec) of the viewport:

```
field_of_view = wwt_widget.get_fov()
center = wwt_widget.get_center()
ra, dec = center.ra, center.dec     # as astropy.coordinates.angles.Longitude, astropy.coordinates.angles.Latitude
ra_deg, dec_deg = ra.deg, dec.deg   # value in degrees
```
We can directly add annotations via Python:

```
# Circles
circle = wwt_widget.add_circle(center)   # Center is an astropy.units.Quantity object
circle = wwt_widget.add_circle()  # Center is the current viewport center
circle.set_center()  # Change center

# Polygons
polygon = wwt_widget.add_polygon(points) # points is an astropy.units.Quantity object

## We can add points later
polygon.add_points(points)

# Lines work similarly to polygons
line = wwt_widget.add_line(points)
line.add_points(points)
```

**Comment by nmearl** [comment]
@Carifio24 Do you also have the example you showed of retrieving the click event coordinates on the WWT plot?

**Comment by patudom** [comment]
@pkgw, do you by chance have easy access to a code snippet that demonstrates the click event coordinate retrieval @nmearl is requesting here?

**Comment by pkgw** [comment]
We're working on that feature right now but it isn't wired all the way into the Python. The browser-side work is in a pull request that Jon just filed, WorldWideTelescope/wwt-webgl-engine#123. I'm just in the process of landing the infrastructure in pywwt that will enable us to plumb everything all the way through.
